// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"
	mock "github.com/stretchr/testify/mock"
)

// IMiddlewares is an autogenerated mock type for the IMiddlewares type
type IMiddlewares struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: h
func (_m *IMiddlewares) Authorize(h *fiber.Ctx) error {
	ret := _m.Called(h)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) error); ok {
		r0 = rf(h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIMiddlewares interface {
	mock.TestingT
	Cleanup(func())
}

// NewIMiddlewares creates a new instance of IMiddlewares. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIMiddlewares(t mockConstructorTestingTNewIMiddlewares) *IMiddlewares {
	mock := &IMiddlewares{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
